package chara.wizard.wand;

public enum Core {
    UNICORN_HAIR,
    DRAGON_HEARTSTRING,
    PHOENIX_FEATHERPHOENIX,
    VEELA_HAIR,
    THESTRAL_TAIL_HAIR,
    TROLL_WHISKER,
    KELPIE_HAIR,
    THUNDERBIRD_TAIL_FEATHER,
    WAMPUS_CAT_HAIR,
    WHITE_RIVER_MONSTER_SPINE,
    ROUGAROU_HAIR,
    KNEAZLE_WHISKERS,
    HORNED_SERPENT_HORN,
    SNALLYGASTER_HEARTSTRING,
    JACKALOPE_ANTLER,
    BASILISK_HORN,
}
